image: ros:dashing

stages:
  - build
  - lint

build-test:
  stage: build
  script:
    - colcon build
    - colcon test --abort-on-error
    
lint-python:
  stage: lint
  script:
    - pip install virtualenv flake8
    - virtualenv venv
    - source venv/bin/activate
    - flake8 --max-line-length=120 --exclude=venv*

lint-cpp:
  stage: lint
  script:
    - apt --quiet install --yes cppcheck
    - cppcheck --error-exitcode=1 .
    #- pip install cpplint
    #- cpplint --extensions=cpp --counting=detailed --linelength=120 --recursive ./*

