image: ubuntu:bionic

before_script:
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes curl gnupg2 lsb-release
  - curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list'
  - apt-get --quiet update --yes
  - apt-get --quiet install --yes ros-dashing-ros-base
  #- apt-get --quiet install --yes python3-colcon-common-extensions cmake build-essential python-rosdep
  - source /opt/ros/dashing/setup.bash

stages:
  - build
  - test

build-colcon:
  stage: build
  script:
    - colcon build

test-colcon:
  stage: test
  script:
    - colcon test --abort-on-error

