image: ros:dashing

stages:
  - build
  - lint

build-test:
  stage: build
  script:
    - colcon build
    - colcon test --abort-on-error
    
lint-python:
  stage: lint
  before_script:
    - pip3 install virtualenv flake8
  script:
    - virtualenv venv
    - source venv/bin/activate
    - python3 -m flake8 --max-line-length=120 --exclude=venv*

lint-cpp:
  stage: lint
  before_script:
    - apt --quiet install --yes cppcheck
    #- pip3 install cpplint
  script:
    - cppcheck --error-exitcode=1 .
    #- cpplint --extensions=cpp --counting=detailed --linelength=120 --recursive ./*
