image: ros:dashing

before_script:
  - apt --quiet update --yes

stages:
  - build
  - lint

build-test:
  stage: build
  script:
    - colcon build
    - colcon test --abort-on-error
    
lint-python:
  stage: lint
  before_script:
    - apt --quiet update --yes
    - apt --quiet install --yes python-pip
    - pip install virtualenv flake8
  script:
    - virtualenv venv
    - source venv/bin/activate
    - flake8 --max-line-length=120 --exclude=venv*

lint-cpp:
  stage: lint
  before_script:
  script:
    - cppcheck --error-exitcode=1 .
